# Generated by Django 3.2.16 on 2022-11-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20221012_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_universitario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Autor')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
