# Generated by Django 3.2.16 on 2022-11-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_pre_universitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pre_universitario',
            options={'verbose_name': 'Pre_universitario', 'verbose_name_plural': 'Pre_universitarios'},
        ),
        migrations.AlterField(
            model_name='pre_universitario',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre del instituto preuniversitario'),
        ),
    ]
