# Generated by Django 3.2.16 on 2022-11-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fecha_nacimineto',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
