# Generated by Django 3.2.16 on 2022-11-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_profesor_fecha_nacimineto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fecha_nacimineto',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
